name: Mirror [prod => prod]
on:
  push:
    branches:
      [prod]

jobs:
  mirror_job:
    runs-on: ubuntu-latest
    name: Mirror 'prod' branch to 'main' branch
    steps:
    - name: Mirror action step
      id: mirror
      uses: google/mirror-branch-action@v1.0
      with:
        github-token: ${{ secrets.GH_TOKEN }}
        source: 'prod'
        dest: 'main'
